@startuml Pedido de Compras
title Modelo de dominio parcial de Pedido de Compras

class       Producto {
                caducidad
                númeroDeSerie
            }
class       EspecificaciónDelProducto {
                descripción
                precio
                productoID
            }
class       Producto
class       EspecificaciónDelProducto
class       FormularioDePedidoDeCompras
class       Depósito
class       Pedido
class       EncargadoDeCompra
class       Lote
class       Caja
class       Anaquel
class       Vitrina
Class       Vacuna
class       RefrigeradorDeVacunas
class       Blister {
                nroDeUnidades
            }
class       Frasco

class       Jarabe
class       Cajón
class       Medicamento

class       Venda
class       Botiquín
class       Inventario

class       Descuento
class       Alerta
class       RecepciónDeProductos
class       CatálogoDeProductos
class       CatálogoDeProveedores
class       CatálogoDeMedicamentosControlados
class       RegistroDeInventario
class       FacturasDeProveedores

note left of Blister::nroDeUnidades
    "Pueden ser pastillas o cápsulas"
end note

EspecificaciónDelProducto "1" -- "*" Producto: "Describe"
EspecificaciónDelProducto "1" -- "*" Blister: "Describe"
Depósito "1" -- "*" Lote: "Está asignado a"
Botiquín "1" -- "*" Venda: "Tiene"
RefrigeradorDeVacunas "1" -- "*" Vacuna: "Está asignado a"

Lote "1" -- "*" Producto: "contiene a"
Lote "1" -- "*" Vacuna: "contiene a"

Jarabe "1" -- "1" Frasco: "esta en un"
Cajón "1" -- "*" Medicamento: "contiene a los"


@enduml