@startuml Gestionar Pedido de Compra
title Registrar pedido
skinparam sequenceMessageAlign center
actor "Personal de Compras" as pc

boundary PedidoCompraUI <<boundary>>
control "PedidoCompraController" as Conexion <<control>>
entity usuarios <<entity>>
entity depositos <<entity>>
entity proveedores <<entity>>
entity pedidocab <<entity>>
entity pedidodet <<entity>>

pc -> PedidoCompraUI: iniciarRegistrarPedidos()


PedidoCompraUI -> Conexion: iniciarConexion()
PedidoCompraUI <-- Conexion: ok


PedidoCompraUI -> Conexion: obtenerUsuarios()
Conexion -> usuarios: obtenerUsuarios()
Conexion <-- usuarios: ok
PedidoCompraUI <-- Conexion: usuarios


PedidoCompraUI -> Conexion: obtenerDepositos()
Conexion -> depositos: obtenerDepositos()
Conexion <-- depositos: ok
PedidoCompraUI <-- Conexion: depositos


PedidoCompraUI -> Conexion: obtenerProveedores()
Conexion -> proveedores: obtenerProveedores()
Conexion <-- proveedores: ok
PedidoCompraUI <-- Conexion: proveedores


pc -> PedidoCompraUI: crearNuevoPedido()

pc -> PedidoCompraUI: introducirProveedor(RUC)
PedidoCompraUI -> PedidoCompraUI: buscarProveedor(RUC)

|||
pc -> PedidoCompraUI: introducirDeposito(depID)
PedidoCompraUI -> PedidoCompraUI: buscarDeposito(depID)

loop "Hasta que se indique"
    pc -> PedidoCompraUI: introducirProducto(prodID, cantidad)
    PedidoCompraUI -> PedidoCompraUI: buscarProducto(depID), agregarProducto(depID)
end
|||
pc -> PedidoCompraUI: registrarPedido(ListaProductos)

PedidoCompraUI -> Conexion: registrarPedido(ListaProductos)
Conexion -> pedidocab: registrarPedido(ListaProductos)


pedidocab -> pedidodet: registrarPedido(ListaProductos)
pedidocab <-- pedidodet: ok

Conexion <-- pedidocab: ok
PedidoCompraUI <-- Conexion: ok
|||
pc <-- PedidoCompraUI: mensajeExito()
@enduml